drop table if exists brands CASCADE;
drop table if exists prices CASCADE;
drop table if exists products CASCADE;
create table brands (id_brand bigint generated by default as identity, name varchar(255), primary key (id_brand));
create table prices (price_list bigint generated by default as identity, curr varchar(255), end_date timestamp, name varchar(255), price double, priority integer not null, start_date timestamp, id_brand bigint, id_product bigint, primary key (price_list));
create table products (id bigint generated by default as identity, name varchar(255), product_id varchar(255), primary key (id));
alter table prices add constraint FKc8v6d9tiw5o7qqotbrxk7rjka foreign key (id_brand) references brands;
alter table prices add constraint FK12jpmndeoqco1sushp9783wak foreign key (id_product) references products;